Removes the MANIFEST file and updates the release scripts

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -13,29 +13,6 @@
 #
 
 # Make a release of hdf4.
-#
-# Programmer: Robb Matzke
-# Creation date: on or before 1998-01-29.
-#
-# Modifications
-#   Robb Matzke, 1999-07-16
-#   The SunOS 5.6 sed *must* have slashes as delimiters. I changed things like
-#   `sed s+/CVS++' to `sed 's/\/CVS//'
-#
-#   Albert Cheng, 1999-10-26
-#   Moved the MANIFEST checking to a separate command file so that
-#   it can be invoked individually.
-#
-#   Albert Cheng, 2004-08-14
-#   Added the --private option.
-#
-#   James Laird, 2005-09-07
-#   Added the md5 method.
-#
-#   Larry Knox, 2017-06-16
-#   Added cmake-tgz and cmake-zip methods
-#   Replaced optional md5 method with automatic md5 checksum generation for
-#   all archives (from hdf5 release script)
 
 # Function definitions
 #
@@ -43,30 +20,28 @@
 USAGE()
 {
 cat << EOF
-Usage: $0 -d <dir> [-h] [--nocheck] [--private] <methods> ...
-   -d <dir>    The name of the directory where the releas(es) should be
+Usage: $0 -d <dir> [-h] [--private] <methods> ...
+   -d DIR       The name of the directory where the release(s) should be
                 placed.
    -h           print the help page.
-   --nocheck    Ignore errors in MANIFEST file.
    --private    Make a private release with today's date in version information.
 
 This must be run at the top level of the source directory.
 The other command-line options are the names of the programs to use
 for compressing the resulting tar archive (if none are given then
 "tar" is assumed):
+
     tar         -- use tar and don't do any compressing.
     gzip        -- use gzip with "-9" and append ".gz" to the output name.
-    cmake-tgz   -- create a tar file using the gzip default level with a
-                   build-unix.sh command file and all other CMake files needed
-                   to build HDF4 source using CMake on unix machines.
     bzip2       -- use bzip2 with "-9" and append ".bz2" to the output name.
-    zip         -- convert all text files to DOS style and form a zip file for
-                   Windows use.
-    cmake-zip   -- convert all text files to DOS style and create a zip file
-                   including cmake scripts and .bat files to build HDF4 source
-                   using CMake on Windows.
+    zip         -- convert all text files to DOS style and form a zip file for Windows use.
+    cmake-tgz   -- create a tar file using the gzip default level with a build-unix.sh
+                   command file and all other CMake files needed to build HDF4 source
+                   using CMake on unix machines.
+    cmake-zip   -- convert all text files to DOS style and create a zip file including cmake
+                   scripts and .bat files to build HDF4 source using CMake on Windows.
 
-An md5 checksum is produced for each archive created and stored in the md5 file.
+A sha256 checksum is produced for each archive created and stored in the sha256 file.
 
 Examples:
 
@@ -94,11 +69,6 @@ EOF
 # Function name: tar2zip
 # Convert the release tarball to a Windows zipball.
 #
-# Programmer: Albert Cheng
-# Creation date: 2014-04-23
-#
-# Modifications
-#
 # Steps:
 # 1. untar the tarball in a temporary directory;
 #    Note: do this in a temporary directory to avoid changing
@@ -119,7 +89,7 @@ tar2zip()
         echo "usage: tar2zip <tarfilename> <zipfilename>"
         return 1
     fi
-    ztmpdir=/tmp/tmpdir$$
+    ztmpdir=/tmp/ztmpdir$$
     mkdir -p $ztmpdir
     version=$1
     tarfile=$2
@@ -141,11 +111,11 @@ tar2zip()
     # -q   quiet mode
     # grep redirect output to /dev/null because -q or -s are not portable.
     find $ztmpdir/$version | \
-    while read inf; do \
-        if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
-        unix2dos -q -k $inf; \
-        fi\
-    done
+        while read inf; do \
+            if file $inf | grep "$inf\: .*text" > /dev/null 2>&1 ; then \
+                unix2dos -q -k $inf; \
+            fi\
+        done
     # step 3: make zipball
     # -9 maximum compression
     # -y Store symbolic links as such in the zip archive
@@ -161,11 +131,6 @@ tar2zip()
 # Function name: tar2cmakezip
 # Convert the release tarball to a Windows zipball with files to run CMake build.
 #
-# Programmer: Larry Knox
-# Creation date: 2017-02-20
-#
-# Modifications
-#
 # Steps:
 # 1. untar the tarball in a temporary directory;
 #    Note: do this in a temporary directory to avoid changing
@@ -178,7 +143,7 @@ tar2zip()
 #        CTestScript.cmake      cmake file copied from <hdf4 source code>/config/cmake/scripts
 #        HDF4config.cmake       cmake file copied from <hdf4 source code>/config/cmake/scripts
 #        HDF4options.cmake      cmake file copied from <hdf4 source code>/config/cmake/scripts
-#        SZip.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
+#        SZIP.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
 #        ZLib.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
 #        JPEG8d.tar.gz          copied from /mnt/scr1/pre-release/hdf4/CMake
 
@@ -201,7 +166,7 @@ tar2cmakezip()
         echo "usage: tar2cmakezip <tarfilename> <zipfilename>"
         return 1
     fi
-    cmziptmpdir=/tmp/cmziptmpdir
+    cmziptmpdir=/tmp/cmziptmpdir$$
     cmziptmpsubdir=$cmziptmpdir/CMake-$HDF4_VERS
     mkdir -p $cmziptmpsubdir
     version=$1
@@ -225,6 +190,8 @@ tar2cmakezip()
     (cd $cmziptmpsubdir; echo "ctest -S HDF4config.cmake,BUILD_GENERATOR=VS201564 -C Release -V -O hdf4.log" > build-VS2015-64.bat; chmod 755 build-VS2015-32.bat)
     (cd $cmziptmpsubdir; echo "ctest -S HDF4config.cmake,BUILD_GENERATOR=VS2017 -C Release -V -O hdf4.log" > build-VS2017-32.bat; chmod 755 build-VS2017-32.bat)
     (cd $cmziptmpsubdir; echo "ctest -S HDF4config.cmake,BUILD_GENERATOR=VS201764 -C Release -V -O hdf4.log" > build-VS2017-64.bat; chmod 755 build-VS2017-64.bat)
+    (cd $cmziptmpsubdir; echo "ctest -S HDF4config.cmake,BUILD_GENERATOR=VS2019 -C Release -V -O hdf4.log" > build-VS2019-32.bat; chmod 755 build-VS2019-32.bat)
+    (cd $cmziptmpsubdir; echo "ctest -S HDF4config.cmake,BUILD_GENERATOR=VS201964 -C Release -V -O hdf4.log" > build-VS2019-64.bat; chmod 755 build-VS2019-64.bat)
 
     # step 3: add SZIP.tar.gz, ZLib.tar.gz and cmake files
     cp /mnt/scr1/pre-release/hdf4/CMake/SZip.tar.gz $cmziptmpsubdir
@@ -246,6 +213,7 @@ tar2cmakezip()
                 unix2dos -q -k $inf; \
             fi\
         done
+
     # step 3: make zipball
     # -9 maximum compression
     # -y Store symbolic links as such in the zip archive
@@ -259,12 +227,8 @@ tar2cmakezip()
 }
 
 # Function name: tar2cmaketgz
-# Convert the release tarball to a Windows zipball with files to run CMake build.
+# Convert the release tarball to a gzipped tar file with files to run CMake build.
 #
-# Programmer: Larry Knox
-# Creation date: 2017-02-20
-#
-# Modifications
 #
 # Steps:
 # 1. untar the tarball in a temporary directory;
@@ -280,7 +244,7 @@ tar2cmakezip()
 #        HDF4options.cmake      cmake file copied from <hdf4 source code>/config/cmake/scripts
 #        SZip.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
 #        ZLib.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
-#        JPEG8d.tar.gz            copied from /mnt/scr1/pre-release/hdf4/CMake
+#        JPEG8d.tar.gz          copied from /mnt/scr1/pre-release/hdf4/CMake
 
 
 # Parameters:
@@ -308,7 +272,7 @@ tar2cmaketgz()
     (cd $cmgztmpsubdir; tar xf -) < $tarfile
     # sanity check
     if [ ! -d $cmgztmpsubdir/$version ]; then
-        echo "untar did not create $cmgztmpdir/$version source dir"
+        echo "untar did not create $cmgztmpsubdir/$version source dir"
         # cleanup
         rm -rf $cmgztmpdir
         return 1
@@ -367,37 +331,34 @@ while [ -n "$1" ]; do
     arg=$1
     shift
     case "$arg" in
-    -d)
-        DEST=$1
-        shift
-        ;;
-    --nocheck)
-        check=no
-        ;;
-    -h)
-        USAGE
-        exit 0
-        ;;
-    --private)
-        pmode=yes
-        ;;
-    -*)
-        echo "Unknown switch: $arg" 1>&2
-        USAGE
-        exit 1
-        ;;
-    *)
-        methods="$methods $arg"
-        ;;
+        -d)
+            DEST=$1
+            shift
+            ;;
+        -h)
+            USAGE
+            exit 0
+            ;;
+        --private)
+            pmode=yes
+            ;;
+        -*)
+            echo "Unknown switch: $arg" 1>&2
+            USAGE
+            exit 1
+            ;;
+        *)
+            methods="$methods $arg"
+            ;;
     esac
 done
 
-# Default methods is tar and md5
+# Default method is tar
 if [ "X$methods" = "X" ]; then
     methods="tar"
 fi
 
-# Create the temporay work directory.
+# Create the temporary work directory.
 if mkdir $tmpdir; then
     echo "temporary work directory for release.  "\
          "Can be deleted after release completes." > $tmpdir/README
@@ -427,22 +388,10 @@ if [ ! -d $DEST ]; then
     exit 1
 fi
 
-# Check the validity of the MANIFEST file.
-bin/chkmanifest || fail=yes
-if [ "X$fail" = "Xyes" ]; then
-    if [ $check = yes ]; then
-        exit 1
-    else
-    echo "Continuing anyway..."
-    fi
-fi
-
-# Create a manifest that contains only files for distribution.
-MANIFEST=$tmpdir/H4_MANIFEST
-grep '^\.' MANIFEST | grep -v _DO_NOT_DISTRIBUTE_ >$MANIFEST
-
-# Prepare the source tree for a release.
+# Create a symlink to the source so files in the tarball have the prefix
+# we want (gnu's --transform isn't portable)
 ln -s `pwd` $tmpdir/$HDF4_VERS || exit 1
+
 # Save a backup copy of Makefile if exists.
 test -f Makefile && mv Makefile $tmpdir/Makefile.x
 cp -p Makefile.dist Makefile
@@ -459,50 +408,46 @@ done
 
 # Create the tar file
 test "$verbose" && echo "   Running tar..." 1>&2
-( \
-    cd $tmpdir; \
-    tar cf $HDF4_VERS.tar $HDF4_VERS/Makefile \
-    `sed 's/^\.\//hdf-'$VERS'\//' $MANIFEST` || exit 1 \
-)
+(cd "$tmpdir" && exec tar -ch --exclude-vcs -f "$HDF4_VERS.tar" "./$HDF4_VERS" || exit 1 )
 
 # Compress
-MD5file=$HDF4_VERS.md5
-cp /dev/null $DEST/$MD5file
+SHA256=$HDF4_VERS.sha256
+cp /dev/null $DEST/$SHA256
 for comp in $methods; do
     case $comp in
-    tar)
-        cp -p $tmpdir/$HDF4_VERS.tar $DEST/$HDF4_VERS.tar
-            (cd $DEST; md5sum $HDF4_VERS.tar >> $MD5file)
-        ;;
-    gzip)
-        test "$verbose" && echo "   Running gzip..." 1>&2
-        gzip -9 <$tmpdir/$HDF4_VERS.tar >$DEST/$HDF4_VERS.tar.gz
-            (cd $DEST; md5sum $HDF4_VERS.tar.gz >> $MD5file)
-        ;;
+        tar)
+            cp -p $tmpdir/$HDF4_VERS.tar $DEST/$HDF4_VERS.tar
+            (cd $DEST; sha256sum $HDF4_VERS.tar >> $SHA256)
+            ;;
+        gzip)
+            test "$verbose" && echo "   Running gzip..." 1>&2
+            gzip -9 <$tmpdir/$HDF4_VERS.tar >$DEST/$HDF4_VERS.tar.gz
+            (cd $DEST; sha256sum $HDF4_VERS.tar.gz >> $SHA256)
+            ;;
         cmake-tgz)
             test "$verbose" && echo "   Creating CMake tar.gz file..." 1>&2
             tar2cmaketgz $HDF4_VERS $tmpdir/$HDF4_VERS.tar $DEST/CMake-$HDF4_VERS.tar.gz 1>&2
-            (cd $DEST; md5sum CMake-$HDF4_VERS.tar.gz >> $MD5file)
+            (cd $DEST; sha256sum CMake-$HDF4_VERS.tar.gz >> $SHA256)
             ;;
-    bzip2)
-        test "$verbose" && echo "   Running bzip2..." 1>&2
-        bzip2 -9 <$tmpdir/$HDF4_VERS.tar >$DEST/$HDF4_VERS.tar.bz2
-            (cd $DEST; md5sum $HDF4_VERS.tar.bz2 >> $MD5file)
-        ;;
-    zip)
-        test "$verbose" && echo "   Creating zip ball..." 1>&2
-        tar2zip $HDF4_VERS $tmpdir/$HDF4_VERS.tar $DEST/$HDF4_VERS.zip 1>&2
-            (cd $DEST; md5sum $HDF4_VERS.zip >> $MD5file)
-        ;;
+        bzip2)
+            test "$verbose" && echo "   Running bzip2..." 1>&2
+            bzip2 -9 <$tmpdir/$HDF4_VERS.tar >$DEST/$HDF4_VERS.tar.bz2
+            (cd $DEST; sha256sum $HDF4_VERS.tar.bz2 >> $SHA256)
+            ;;
+        zip)
+            test "$verbose" && echo "   Creating zip ball..." 1>&2
+            tar2zip $HDF4_VERS $tmpdir/$HDF4_VERS.tar $DEST/$HDF4_VERS.zip 1>&2
+            (cd $DEST; sha256sum $HDF4_VERS.zip >> $SHA256)
+            ;;
         cmake-zip)
             test "$verbose" && echo "   Creating CMake-zip ball..." 1>&2
             tar2cmakezip $HDF4_VERS $tmpdir/$HDF4_VERS.tar $DEST/CMake-$HDF4_VERS.zip 1>&2
-            (cd $DEST; md5sum CMake-$HDF4_VERS.zip >> $MD5file)
+            (cd $DEST; sha256sum CMake-$HDF4_VERS.zip >> $SHA256)
             ;;
-    *)
-        echo "***Error*** Unknown method $comp"
-        exit 1
-        ;;
+        *)
+            echo "***Error*** Unknown method $comp"
+            exit 1
+            ;;
     esac
 done
 
@@ -521,5 +466,7 @@ fi
 
 # Remove temporary things
 rm -rf $tmpdir
+
+echo "DONE"
 
 exit 0
