Purpose: Feature
Description:
Added the deploy feature.  When the build is successful and if deploy
is requested, the binary will be installed under what deploydir defined
as.

Platforms tested:
Heping.

diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -73,6 +73,29 @@ while [ $# -gt 0 ] ; do
 	    cmddiff="diff"
 	    cmd=""
 	    ;;
+	deploy)
+	    # deploy the built binary.
+	    shift
+	    if [ $# -lt 1 ]; then
+		echo "deploy <dir> missing"
+		errcode=1
+		cmd="help"
+		break
+	    fi
+	    cmddeploy="deploy"
+	    DEPLOYDIRNAME="$1"
+	    ;;
+	deploydir)
+	    # default directory for deployment.
+	    shift
+	    if [ $# -lt 1 ]; then
+		echo "deploydir <dir> missing"
+		errcode=1
+		cmd="help"
+		break
+	    fi
+	    deploydir="$1"
+	    ;;
 	test)
 	    cmdtest="test"
 	    cmd=""
@@ -154,13 +177,16 @@ if [ "$cmd" = help ]; then
     set -
     cat <<EOF
 Usage: $PROGNAME [all] [checkout] [diff] [test] [srcdir] [release] [help]
-          [zlib <zlib_path>] [archive <arch_path>] [dir <dir>]
-	  [op-configure <option>] [--<option>]
+	[clean] [distclean] [echo] [deploy <dir>] [deploydir <dir>]
+	[zlib <zlib_path>] [archive <arch_path>] [srcdirname <dir>]
+	[op-configure <option>] [--<option>]
     all:      Run all commands (checkout, test & release)
               [Default is all]
     checkout: Run cvs checkout
     diff:     Run diff on current and previous versions.  Exit 0 if
               no significant differences are found.  Otherwise, non-zero.
+    deploy:   deploy binary to directory <dir>
+    deploydir: use <dir> as the default directory for deployment
     test:     Run test
     release:  Run release
     clean:    Run make clean
@@ -332,6 +358,20 @@ if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
 	fi
     fi
 fi # Test the HDF4 library
+
+
+#=============================
+# Run deployment if requested.
+#=============================
+if [ -n "$DEPLOYDIRNAME" ]; then
+    if [ "$snapshot" = "yes" ]; then
+	TIMESTAMP "deploy"
+	if (cd ${TESTDIR} && ${CURRENT}/bin/deploy ${deploydir}/${DEPLOYDIRNAME}); then
+	    errcode=$?
+	    exit $errcode
+	fi
+    fi
+fi # Deploy
 
 
 #=============================
