A minor lex fix for the SGI and fixed formatting in Makefile.in

diff --git a/mfhdf/ncgen/Makefile.in b/mfhdf/ncgen/Makefile.in
--- a/mfhdf/ncgen/Makefile.in
+++ b/mfhdf/ncgen/Makefile.in
@@ -5,8 +5,8 @@
 PROGRAM		= ncgen
 BINFILES	= $(PROGRAM)
 CPP_NETCDF	= -I../libsrc
-CPPFLAGS	= $(CPP_NETCDF) @CPPFLAGS@
-CFLAGS		= @CFLAGS@ @HDF_INC@
+CPPFLAGS	= $(CPP_NETCDF) @CPPFLAGS@ @HDF_INC@
+CFLAGS		= @CFLAGS@
 FFLAGS		= @FFLAGS@
 MANUALS		= ncgen.1
 GARBAGE		= $(PROGRAM) \
@@ -20,13 +20,13 @@ MANIFEST	= Makefile.in depend README \
 		  main.c make.com msoft.mk msofttab.c msofttab.h \
 		  msoftyy.c ncgen.1 ncgen.h ncgen.l ncgen.opt ncgen.y \
 		  test.com test0.cdl \
-                  $(vms_stuff)
+		  $(vms_stuff)
 LIBNAME		= netcdf
-LD_NETCDF	= -L../libsrc -l$(LIBNAME)
+LD_NETCDF	= -L../libsrc -l$(LIBNAME) @HDF_LIB@
 OBJS		= main.o generate.o load.o ncgentab.o escapes.o \
 		  getfill.o init.o close.o genlib.o
 LD_XDR		= @LD_XDR@
-LIBS		= $(LD_NETCDF) $(LD_XDR) @HDF_LIB@
+LIBS		= $(LD_NETCDF) $(LD_XDR)
 LEX		= @LEX@
 YACC		= @YACC@
 prefix		= ../../..
@@ -51,7 +51,7 @@ ncgenyy.c:	ncgen.l
 
 # The SunOS 4.1.3 yacc(1) doesn't generate correct code.
 #
-vms-stuff:    ncgentab.h ncgentab.c ncgenyy.c
+vms-stuff:	ncgentab.h ncgentab.c ncgenyy.c
 	cp ncgentab.h vmstab.h
 	cp ncgentab.c vmstab.c
 	cp ncgenyy.c vms_yy.c
@@ -81,29 +81,29 @@ ctest0:		ncgen test0.cdl
 #
 # test "-f" option of ncgen
 #
-ftest:                test1.cdl
-        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
-            $(MAKE) $(MFLAGS) ftest0; \
-            ./ftest0            # tests `-f' option, creates ftest0.nc; \
-            $(NCDUMP) -n test1 ftest0.nc > ftest1.cdl; \
-            if diff test1.cdl ftest1.cdl; then \
-                echo "*** ncgen -f test successful ***"; \
-            else \
-                echo "*** ncgen -f test failed " \
-                    "(but roundoff differences are OK) ***"; \
-            fi; \
-        else \
-            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
-        fi
+ftest:		test1.cdl
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
+	    $(MAKE) $(MFLAGS) ftest0; \
+	    ./ftest0		# tests `-f' option, creates ftest0.nc; \
+	    $(NCDUMP) -n test1 ftest0.nc > ftest1.cdl; \
+	    if diff test1.cdl ftest1.cdl; then \
+		echo "*** ncgen -f test successful ***"; \
+	    else \
+		echo "*** ncgen -f test failed " \
+		    "(but roundoff differences are OK) ***"; \
+	    fi; \
+	else \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+	fi
 
-ftest0:               $(PROGRAM) test0.cdl
-        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
-            $(MAKE) $(MFLAGS) netcdf.inc; \
-            ./$(PROGRAM) -f -o ftest0.nc test0.cdl > test0.f; \
-            $(FC) $(FFLAGS) -o $@ test0.f $(LIBS); \
-        else \
-            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
-        fi
+ftest0:		$(PROGRAM) test0.cdl
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
+	    $(MAKE) $(MFLAGS) netcdf.inc; \
+	    ./$(PROGRAM) -f -o ftest0.nc test0.cdl > test0.f; \
+	    $(FC) $(FFLAGS) -o $@ test0.f $(LIBS); \
+	else \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+	fi
 
 test1.cdl:	test0.nc
 	$(NCDUMP) -n test1 test0.nc > $@
@@ -112,11 +112,11 @@ test0.nc:	$(PROGRAM) test0.cdl
 	./$(PROGRAM) -b -o test0.nc test0.cdl
 
 netcdf.inc:
-        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
-            ln -s ../fortran/$@ .; \
-        else \
-            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
-        fi
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
+	    ln -s ../fortran/$@ .; \
+	else \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+	fi
 
 include ../port/master.mk
 
