Fixed error reporting when customize file is not found.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -125,7 +125,7 @@ fi
 
 # make sure host specific custom_xxx is there
 if [ ! -f ${srcdir}/${files} ]; then
-    echo '***' "We are missing host specific customize file ${host_makefile_frag}" 1>&2
+    echo '***' "We are missing host specific customize file ${files}" 1>&2
     echo '***' "Please read the installation docs" 1>&2
     exit 1
 fi
diff --git a/hdf/jpeg/configure.in b/hdf/jpeg/configure.in
--- a/hdf/jpeg/configure.in
+++ b/hdf/jpeg/configure.in
@@ -114,7 +114,7 @@ fi
 
 # make sure host specific 'jconfig.h' is there
 if [ ! -f ${srcdir}/${files} ]; then
-    echo '***' "We are missing host specific ${host_makefile_frag}" 1>&2
+    echo '***' "We are missing host specific ${files}" 1>&2
     echo '***' "Please read the installation docs" 1>&2
     exit 1
 fi
