Purpose: Fixed bugzilla 558 cont.
Description:
    Added tests to testutil.sh.in to test hdfimport taking an hdf file
    as input.  Also, added
        SDSfloat2.hdf - hdf file containing a two-dim SDS with float32 data
        SDSfloat3.hdf - hdf file containing a three-dim SDS with float32 data
        crtSDSfloats.c - program that generated the two hdf files above
        hdfimport.out3 - file to verify test output.

Platforms tested:
    Linux 2.4 (heping)
    SunOS 5.9 (shanti)
    AIX 5.1 (copper)

diff --git a/mfhdf/hdfimport/testutil.sh.in b/mfhdf/hdfimport/testutil.sh.in
--- a/mfhdf/hdfimport/testutil.sh.in
+++ b/mfhdf/hdfimport/testutil.sh.in
@@ -32,7 +32,7 @@ echo "=============================="
 if [ -f hdfimport -a -f hdfimporttest ]; then
 echo "** Testing hdfimport  ***"
 
-/bin/rm -f ctxt* cb* *.hdf hdfls.tmp5 hdfed.tmp6
+/bin/rm -f ctxt* cb* *.hdf *.out hdfls.tmp5 hdfed.tmp6 hdffiles.tmp
 ${TESTS_ENVIRONMENT} ./hdfimporttest
 echo "Testing for 32-bit floating point ASCII (2D data)" 
 $TESTCMD ctxtr2 -o ctxtr2.hdf
@@ -61,6 +61,12 @@ $TESTCMD cb64r3 -n -o cb64r3-n.hdf
 echo "Testing for raster options" 
 $TESTCMD ctxtr2 -o ctxtr2_ris.hdf -raster -e 50 50
 $TESTCMD cb64r2 -o cb64r2_ris.hdf -raster -i 50 50 -f
+
+# test with hdf files
+echo "Testing for reading from hdf files" 
+$TESTCMD $srcdir/SDSfloat2.hdf -o SDSfloat2.out
+$TESTCMD $srcdir/SDSfloat3.hdf -o SDSfloat3.out
+
 ($HDFLS -l ctxtr2.hdf | $SED) > hdfls.tmp5 2>&1
 ($HDFLS -l ctxtr3.hdf | $SED) >> hdfls.tmp5 2>&1
 ($HDFLS -l cb32i2.hdf | $SED) >> hdfls.tmp5 2>&1
@@ -76,11 +82,20 @@ $TESTCMD cb64r2 -o cb64r2_ris.hdf -raster -i 50 50 -f
 ($HDFLS -l ctxtr2_ris.hdf | $SED) >> hdfls.tmp5 2>&1
 ($HDFLS -l cb64r2_ris.hdf | $SED) >> hdfls.tmp5 2>&1
 
+# run hdfls on SDSfloat*.out, and remove the library version from the
+# output for later checking agains original output - BMR (2006/9/7)
+($HDFLS SDSfloat2.out | $SED) >> hdffiles.tmp 2>&1
+($HDFLS SDSfloat3.out | $SED) >> hdffiles.tmp 2>&1
+
     diff  hdfls.tmp5 $srcdir/hdfimport.out1 || errors=1
     $HDFEDCMD < $srcdir/hdfimport.input1 > hdfed.tmp6 2>&1
     diff  hdfed.tmp6 $srcdir/hdfimport.out2 || errors=1
 
-/bin/rm -f ctxt* cb* *.hdf hdfls.tmp5 hdfed.tmp6
+    # hdfimport.out3 contains output that hdfls previously generated
+    # from SDSfloat*.out with the library version removed - BMR (2006/9/7)
+    diff  hdffiles.tmp $srcdir/hdfimport.out3 || errors=1
+
+/bin/rm -f ctxt* cb* *.hdf *.out hdfls.tmp5 hdfed.tmp6 hdffiles.tmp
 #/bin/rm -f ctxt* cb* *.hdf 
 else
 haserr=1
@@ -111,6 +126,8 @@ if [ $errors -eq 1 ]; then
   echo " $TESTCMD cb64r3 -n -o cb64r3-n.hdf "
   echo " $TESTCMD ctxtr2 -o ctxtr2_ris.hdf -raster -e 50 50 "
   echo " $TESTCMD cb64r2 -o cb64r2_ris.hdf -raster -i 50 50 -f "
+  echo " $TESTCMD SDSfloat2.hdf -o SDSfloat2.out "
+  echo " $TESTCMD SDSfloat3.hdf -o SDSfloat3.out "
   echo "($HDFLS -l ctxtr2.hdf | $SED) >&  hdfls.tmp5 "
   echo "($HDFLS -l ctxtr3.hdf | $SED) >>& hdfls.tmp5 "
   echo "($HDFLS -l cb32i2.hdf | $SED) >> hdfls.tmp5 2>&1 "
@@ -125,9 +142,12 @@ if [ $errors -eq 1 ]; then
   echo "($HDFLS -l cb64r3-n.hdf | $SED) >> hdfls.tmp5 2>&1 "
   echo "($HDFLS -l ctxtr2_ris.hdf | $SED) >>& hdfls.tmp5 "
   echo "($HDFLS -l cb64r2_ris.hdf | $SED) >>& hdfls.tmp5 "
+  echo "($HDFLS SDSfloat2.out | $SED) >> hdffiles.tmp 2>&1 "
+  echo "($HDFLS SDSfloat3.out | $SED) >> hdffiles.tmp 2>&1 "
   echo " diff hdfls.tmp5 hdfimport.out1 "
   echo " $HDFEDCMD < hdfimport.input1 >& hdfed.tmp6 "
   echo " diff hdfed.tmp6 hdfimport.out2 "
+  echo " diff  hdffiles.tmp hdfimport.out3 || errors=1 "
   echo " ******* END NOTE *************"
   echo ""
   errors=0
