Update CMake to match hdf5

diff --git a/config/cmake/libh4cc.in b/config/cmake/libh4cc.in
--- a/config/cmake/libh4cc.in
+++ b/config/cmake/libh4cc.in
@@ -1,7 +1,6 @@
 #! /bin/sh
 ##
 # Copyright by The HDF Group.
-# Copyright by the Board of Trustees of the University of Illinois.
 # All rights reserved.
 #
 # This file is part of HDF.  The full HDF copyright notice, including
@@ -22,21 +21,43 @@ fi
 dir=$(
   cd -P -- "$(dirname -- "$prg")/.." && pwd -P
 ) || exit
-prg=$dir/$(basename -- "$prg") || exit
+prg=$dir/bin/$(basename -- "$prg") || exit
 
-printf '%s\n' "$prg"
-printf 'dir is %s\n' "$dir"
+#printf '%s\n' "$prg"
+#printf 'dir is %s\n' "$dir"
 
+pc_args=""
 
 # Show the configuration summary of the library recorded in the
 # libhdf4.settings file residing in the lib directory.
 showconfigure()
 {
-  cat $dir/lib/libhdf4.settings
+  cat $dir/@HDF4_INSTALL_LIB_DIR@/libhdf4.settings
   status=$?
 }
 
-export PKG_CONFIG_PATH=$dir/lib/pkgconfig
+usage() {
+  # "How-to use" message.
+  echo "usage: $prg [OPTIONS] <pkg-config line>"
+  echo "  OPTIONS:"
+  echo "    -help           This help message."
+  echo "    -show           Show the commands without executing them"
+  echo "    -showconfig     Show the HDF4 library configuration summary"
+  echo " "
+  echo "  <pkg-config line> - the pkg-config compile line options for the compiler"
+  echo "                    that was used to compile HDF4." 
+  echo "                    Use pkg-config --help for more information"
+  echo "                    on which options are available. $prg passes pkg-config options"
+  echo "                    through as those options use double-underscores."
+  echo " "
+  echo "                    NOTE: pkg-config is required to be installed on your system and"
+  echo "                    using --static requires a static version of the C runtime library"
+  echo "                    to be have been installed on your system."
+  echo " "
+  exit $EXIT_FAILURE
+}
+
+export PKG_CONFIG_PATH=$dir/@HDF4_INSTALL_LIB_DIR@/pkgconfig
 
 for arg in $@ ; do
   case "$arg" in
@@ -44,8 +65,21 @@ for arg in $@ ; do
       showconfigure
       exit $status
       ;;
+    -show)
+      shift
+      echo @_PKG_CONFIG_COMPILER@ "$@" `pkg-config $pc_args --define-variable=prefix=$dir --cflags --libs @_PKG_CONFIG_LIBNAME@`
+      exit $status
+      ;;
+    -help)
+      usage
+      exit $status
+      ;;
+    --*)
+      # gather pkg-config specific options
+      pc_args="$pc_args $arg"
+      ;;
     *)
-      @_PKG_CONFIG_COMPILER@ $@ `pkg-config --define-variable=prefix=$dir --cflags --libs @_PKG_CONFIG_LIBNAME@`
+      @_PKG_CONFIG_COMPILER@ "$@" `pkg-config $pc_args --define-variable=prefix=$dir --cflags --libs @_PKG_CONFIG_LIBNAME@`
       status=$?
       exit $status
       ;;
