Integrated changes in netCDF 2.3 Final Release

diff --git a/mfhdf/doc/Makefile b/mfhdf/doc/Makefile
--- a/mfhdf/doc/Makefile
+++ b/mfhdf/doc/Makefile
@@ -4,16 +4,18 @@
 # $Id$
 
 MANUALS		= netcdf.3 netcdf.3f
+INFOS		= guide.info
 MANIFEST	= README Makefile.in \
 		  $(MANUALS) texindex.c udunits.dat guide.ps guide.txn \
 		  texinfo.tex 
 prefix		= /hdf/home/chouck/hdf
-GARBAGE		= *.log *~ *.gs *.aux *.cp *.fn *.ky *.pg *.toc *.tp *.vr
+GARBAGE		= $(INFOS) *.log *~ *.gs *.aux *.cp *.fn *.ky *.pg *.toc \
+		  *.tp *.vr
 PRINTER		= hpnp
 
 all::
 
-install::	installed_manuals
+install::	installed_manuals installed_infos
 
 guide.hc:	guide.ps
 	lpr -P$(PRINTER) guide.ps
@@ -48,6 +50,7 @@ INSTALL		= /bin/install -c
 INSTALL_DATA	= $(INSTALL) -m 664
 INSTALL_PROGRAM	= $(INSTALL)
 FC		= f77
+MAKEINFO        = 
 NCDUMP		= @NCDUMP@
 NCGEN		= @NCGEN@
 NEQN		= neqn
@@ -379,6 +382,62 @@ dummy_mandir $(MANDIR):
 	mkdir -p $@
 	chmod u+rwx,g+rws,o=rx $@
 
+############################################################################
+# TeX-Info Pages:
+############################################################################
+INFODIR       = $(prefix)/info
+
+installed_infos:      FORCE
+	if [ -z "$(MAKEINFO)" ]; then \
+		echo 1>&2 "Can't install info(1) pages because no makeinfo(1)"; \
+	else \
+	  if [ -n "$(INFOS)" ]; then \
+	      infos="$(INFOS)"; \
+	      for info in $$infos; do \
+		$(MAKE) $(MFLAGS) INFODIR=$(INFODIR) INFO=$$info \
+		installed_info || exit 1; \
+	      done; \
+	   else \
+	      :; \
+	   fi; \
+	fi;
+# The following target decouples the previous targets from the actual rule;
+# thus, eliminating extraneous make(1) messages.
+#
+installed_info:       $(INFODIR)/$(INFO)
+
+$(INFODIR)/$(INFO):   $(INFODIR) $(INFO)
+	$(INSTALL_DATA) $(INFO) $@
+
+dummy_infodir $(INFODIR):
+	mkdir -p $@
+	chmod u+rwx,g+rws,o=rx $@
+
+# Rules for generating info pages:
+#
+.SUFFIXES:    .info .texi .texinfo .txn
+.texi.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.texinfo.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.txn.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+
+# Ensure that info page depends on canonical TeX-Info macros.
+#
+dummy_info $(INFO):   texinfo.tex
 
 ############################################################################
 # Cleanup:
@@ -503,6 +562,7 @@ MANIFEST.echo:	FORCE
 	    subdirs="$(SUBDIRS)"; \
 	    for subdir in $$subdirs; do \
 		(cd $$subdir && \
+                echo 1>&2 Creating $@ in `pwd` && \
 		$(MAKE) $(MFLAGS) MANIFEST.echo | \
 		    sed "s|^|$$subdir/|") || exit 1; \
 	    done; \
diff --git a/mfhdf/fortran/Makefile b/mfhdf/fortran/Makefile
--- a/mfhdf/fortran/Makefile
+++ b/mfhdf/fortran/Makefile
@@ -4,13 +4,12 @@
 # $Id$
 
 PROGRAM		= ftest
-OS		= irix
+OS		= sunos
 FC		= f77
-CPP_NETCDF	= -I../libsrc -I/hdf/home/chouck/hdf/33/include -DIRIS4 -cckr
-CPP_OLD_FILLVALUES	= 
-CPPFLAGS	= $(CPP_NETCDF) $(CPP_OLD_FILLVALUES) -DNDEBUG -DHDF -DNO_STRERROR
+CPP_NETCDF	= -I../libsrc -I/hdf/home/chouck/hdf/33/include -DSUN
+CPPFLAGS	= $(CPP_NETCDF) -DNDEBUG -DHDF -DNO_HAVE_PROTOTYPES -Dconst= -DNO_STDARG -DNO_STRERROR
 CFLAGS		= -g
-FFLAGS		= -O
+FFLAGS		= 
 HDF_LIB         = /hdf/home/chouck/hdf/33/lib/libdf.a
 GARBAGE		= $(PROGRAM) test.nc copy.nc netcdf.inc jackets.c \
 		  $(PROGRAM).f test*.hdf hdftest hdfout.new
@@ -18,38 +17,50 @@ HEADERS		= netcdf.inc
 MANIFEST	= $(PROGRAM).src Makefile.in README aix.m4 common.inc \
 		  common.m4 depend descrip.mms fortc fortc1.sed \
 		  fortc2.sed hpux.m4 irix.m4 jackets.src msoft.m4 msoft.mk \
-		  sunos.m4 ultrix.m4 unicos.m4 vms.m4 \
+		  next.m4 osf.m4 sunos.m4 ultrix.m4 unicos.m4 vms.m4 \
 		  msoft/NOTES msoft/fslen.asm msoft/ftest.for \
 		  msoft/jackets.c msoft/msoft.int \
-		  msoft/netcdf.inc
+		  msoft/netcdf.inc \
+		  vms/ftest.for \
+		  vms/ftest.m4 \
+		  vms/jackets.c \
+		  vms/make.com \
+		  vms/netcdf.inc \
+		  mfsdf.c mfsdff.f hdftest.f
 
 LIBOBJS		= jackets.o mfsdf.o mfsdff.o
 LIBNAME		= netcdf
-LIBRARY		= ../libsrc/lib$(LIBNAME).a
+REMOTE_LIBRARY	= ../libsrc/lib$(LIBNAME).a
 OBJS		= $(PROGRAM).o $(LIBOBJS) 
-LD_XDR		= -lsun
+LD_XDR		= 
 LD_NETCDF	= -L../libsrc -lnetcdf
 LIBS		= $(LD_NETCDF) $(LD_XDR) $(HDF_LIB)
 prefix		= /hdf/home/chouck/hdf
 
-all::		netcdf.inc $(LIBRARY)
+all::		FORCE
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
+	    $(MAKE) netcdf.inc $(REMOTE_LIBRARY); \
+	else \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+	fi
 
 test:		FORCE
-	@if [ -n "$(FC)" ]; then \
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
 	    $(MAKE) $(MFLAGS) $(PROGRAM); \
 	    $(MAKE) $(MFLAGS) hdftest; \
 	    ./$(PROGRAM); \
 	else \
-	    echo "\`$@' not made because FORTRAN macro FC unset"; \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
 	fi
 
-install::	installed_headers
+install::	FORCE
+	@if [ `which "$(FC)" | wc -w` = 1 ]; then \
+	    $(MAKE) installed_headers; \
+	else \
+	    echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+	fi
 
-$(LIBRARY):	$(LIBOBJS)
-	$(AR) rcuv $@ $?
-	$(RANLIB) $@
-
-$(PROGRAM):	$(PROGRAM).o $(LIBRARY)
+$(PROGRAM):	$(REMOTE_LIBRARY)
 
 jackets.c:	fortc1.sed fortc2.sed common.m4 jackets.src $(OS).m4
 	./fortc -L . -O $(OS) jackets.src > $@
@@ -91,14 +102,15 @@ AR		= ar
 CC		= cc
 CPP		= cc -E
 INCDIR		= $(prefix)/include
-INSTALL		= cp
-INSTALL_DATA	= $(INSTALL)
+INSTALL		= /bin/install -c
+INSTALL_DATA	= $(INSTALL) -m 664
 INSTALL_PROGRAM	= $(INSTALL)
 FC		= f77
+MAKEINFO        = 
 NCDUMP		= @NCDUMP@
 NCGEN		= @NCGEN@
 NEQN		= neqn
-OS		= irix
+OS		= sunos
 SHELL		= /bin/sh
 TBL		= tbl
 
@@ -426,6 +438,62 @@ dummy_mandir $(MANDIR):
 	mkdir -p $@
 	chmod u+rwx,g+rws,o=rx $@
 
+############################################################################
+# TeX-Info Pages:
+############################################################################
+INFODIR       = $(prefix)/info
+
+installed_infos:      FORCE
+	if [ -z "$(MAKEINFO)" ]; then \
+		echo 1>&2 "Can't install info(1) pages because no makeinfo(1)"; \
+	else \
+	  if [ -n "$(INFOS)" ]; then \
+	      infos="$(INFOS)"; \
+	      for info in $$infos; do \
+		$(MAKE) $(MFLAGS) INFODIR=$(INFODIR) INFO=$$info \
+		installed_info || exit 1; \
+	      done; \
+	   else \
+	      :; \
+	   fi; \
+	fi;
+# The following target decouples the previous targets from the actual rule;
+# thus, eliminating extraneous make(1) messages.
+#
+installed_info:       $(INFODIR)/$(INFO)
+
+$(INFODIR)/$(INFO):   $(INFODIR) $(INFO)
+	$(INSTALL_DATA) $(INFO) $@
+
+dummy_infodir $(INFODIR):
+	mkdir -p $@
+	chmod u+rwx,g+rws,o=rx $@
+
+# Rules for generating info pages:
+#
+.SUFFIXES:    .info .texi .texinfo .txn
+.texi.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.texinfo.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.txn.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+
+# Ensure that info page depends on canonical TeX-Info macros.
+#
+dummy_info $(INFO):   texinfo.tex
 
 ############################################################################
 # Cleanup:
@@ -550,6 +618,7 @@ MANIFEST.echo:	FORCE
 	    subdirs="$(SUBDIRS)"; \
 	    for subdir in $$subdirs; do \
 		(cd $$subdir && \
+                echo 1>&2 Creating $@ in `pwd` && \
 		$(MAKE) $(MFLAGS) MANIFEST.echo | \
 		    sed "s|^|$$subdir/|") || exit 1; \
 	    done; \
diff --git a/mfhdf/libsrc/Makefile b/mfhdf/libsrc/Makefile
--- a/mfhdf/libsrc/Makefile
+++ b/mfhdf/libsrc/Makefile
@@ -4,9 +4,8 @@
 # $Id$
 
 PROGRAM		= cdftest
-CPP_OLD_FILLVALUES	= 
-CPPFLAGS	= $(CPP_OLD_FILLVALUES) -DNDEBUG -DHDF -DNO_STRERROR
-CFLAGS		= -g -I/hdf/home/chouck/hdf/33/include -DIRIS4 -cckr
+CPPFLAGS	= -DNDEBUG -DHDF -DNO_HAVE_PROTOTYPES -Dconst= -DNO_STDARG -DNO_STRERROR
+CFLAGS		= -g -I/hdf/home/chouck/hdf/33/include -DSUN
 GARBAGE		= $(PROGRAM) test.cdf cdfout.new test*.hdf \
                   hdftest hdfout.new
 HEADERS		= netcdf.h
@@ -20,8 +19,7 @@ MANIFEST	= Makefile.in README \
 		  $(CSRCS) cdftest.c \
 		  alloc.h testout.sav descrip.mms error.h htons.mar \
 		  local_nc.h make.com msoft.mk netcdf.h ntohs.mar \
-		  test_cdf.sav hdfout.sav mfsd.c hdfpg.c hdfcdf.c \
-                  hdfsds.c
+		  test_cdf.sav hdfout.sav mfsd.c hdfsds.c hdftest.c
 LIBOBJS		= array.o attr.o cdf.o dim.o file.o iarray.o error.o \
 		  globdef.o putget.o putgetg.o sharray.o string.o var.o \
 		  xdrposix.o hdfsds.o mfsd.o
@@ -29,7 +27,7 @@ LIBRARY		= netcdf
 DEBUGLIBRARY	= netcdf_g
 PROFILEDLIBRARY	= netcdf_pg
 OBJS		= $(PROGRAM).o
-LD_XDR		= -lsun
+LD_XDR		= 
 LD_NETCDF	= -L. -lnetcdf
 LIBS		= $(LD_NETCDF) $(LD_XDR) $(HDF_LIB)
 prefix		= /hdf/home/chouck/hdf
@@ -109,14 +107,15 @@ AR		= ar
 CC		= cc
 CPP		= cc -E
 INCDIR		= $(prefix)/include
-INSTALL		= cp
-INSTALL_DATA	= $(INSTALL)
+INSTALL		= /bin/install -c
+INSTALL_DATA	= $(INSTALL) -m 664
 INSTALL_PROGRAM	= $(INSTALL)
 FC		= f77
+MAKEINFO        = 
 NCDUMP		= @NCDUMP@
 NCGEN		= @NCGEN@
 NEQN		= neqn
-OS		= irix
+OS		= sunos
 SHELL		= /bin/sh
 TBL		= tbl
 
@@ -444,6 +443,62 @@ dummy_mandir $(MANDIR):
 	mkdir -p $@
 	chmod u+rwx,g+rws,o=rx $@
 
+############################################################################
+# TeX-Info Pages:
+############################################################################
+INFODIR       = $(prefix)/info
+
+installed_infos:      FORCE
+	if [ -z "$(MAKEINFO)" ]; then \
+		echo 1>&2 "Can't install info(1) pages because no makeinfo(1)"; \
+	else \
+	  if [ -n "$(INFOS)" ]; then \
+	      infos="$(INFOS)"; \
+	      for info in $$infos; do \
+		$(MAKE) $(MFLAGS) INFODIR=$(INFODIR) INFO=$$info \
+		installed_info || exit 1; \
+	      done; \
+	   else \
+	      :; \
+	   fi; \
+	fi;
+# The following target decouples the previous targets from the actual rule;
+# thus, eliminating extraneous make(1) messages.
+#
+installed_info:       $(INFODIR)/$(INFO)
+
+$(INFODIR)/$(INFO):   $(INFODIR) $(INFO)
+	$(INSTALL_DATA) $(INFO) $@
+
+dummy_infodir $(INFODIR):
+	mkdir -p $@
+	chmod u+rwx,g+rws,o=rx $@
+
+# Rules for generating info pages:
+#
+.SUFFIXES:    .info .texi .texinfo .txn
+.texi.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.texinfo.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.txn.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+
+# Ensure that info page depends on canonical TeX-Info macros.
+#
+dummy_info $(INFO):   texinfo.tex
 
 ############################################################################
 # Cleanup:
@@ -568,6 +623,7 @@ MANIFEST.echo:	FORCE
 	    subdirs="$(SUBDIRS)"; \
 	    for subdir in $$subdirs; do \
 		(cd $$subdir && \
+                echo 1>&2 Creating $@ in `pwd` && \
 		$(MAKE) $(MFLAGS) MANIFEST.echo | \
 		    sed "s|^|$$subdir/|") || exit 1; \
 	    done; \
@@ -589,7 +645,6 @@ FORCE:
 
 ### Everything after the following line might be overwritten ###
 ### DO NOT DELETE THIS LINE.  make depend DEPENDS ON IT ###
-arg.o: arg.c
 array.o: array.c
 array.o: ./local_nc.h
 array.o: ./netcdf.h
@@ -602,8 +657,6 @@ cdf.o: cdf.c
 cdf.o: ./local_nc.h
 cdf.o: ./netcdf.h
 cdf.o: ./alloc.h
-cdftest-gt.o: cdftest-gt.c
-cdftest-gt.o: ./netcdf.h
 cdftest.o: cdftest.c
 cdftest.o: ./netcdf.h
 dim.o: dim.c
@@ -613,37 +666,27 @@ dim.o: ./alloc.h
 error.o: error.c
 error.o: ./local_nc.h
 error.o: ./netcdf.h
-externinit.o: externinit.c
-externinit.o: ./netcdf.h
-file-144.o: file-144.c
-file-144.o: ./local_nc.h
-file-144.o: ./netcdf.h
-file-144.o: ./alloc.h
-file-fin.o: file-fin.c
-file-fin.o: ./netcdf.h
 file.o: file.c
 file.o: ./local_nc.h
 file.o: ./netcdf.h
 file.o: ./alloc.h
 globdef.o: globdef.c
 globdef.o: ./netcdf.h
+hdfsds.o: hdfsds.c
+hdfsds.o: ./local_nc.h
+hdfsds.o: ./netcdf.h
+hdftest.o: hdftest.c
+hdftest.o: ./mfsd.h
+hdftest.o: ./local_nc.h
+hdftest.o: ./netcdf.h
 iarray.o: iarray.c
 iarray.o: ./local_nc.h
 iarray.o: ./netcdf.h
 iarray.o: ./alloc.h
-nc.o: nc.c
-nc.o: ./nc.h
-nc.o: ./netcdf.h
-nctime.o: nctime.c
-nctime.o: ./timing.h
-nctime.o: ./netcdf.h
-ncvgt.o: ncvgt.c
-ncvgt.o: ./netcdf.h
-obioread.o: obioread.c
-obioread.o: ./timing.h
-ofread.o: ofread.c
-ofread.o: ./timing.h
-posix.o: posix.c
+mfsd.o: mfsd.c
+mfsd.o: ./mfsd.h
+mfsd.o: ./local_nc.h
+mfsd.o: ./netcdf.h
 putget.o: putget.c
 putget.o: ./local_nc.h
 putget.o: ./netcdf.h
@@ -651,51 +694,24 @@ putget.o: ./alloc.h
 putgetg.o: putgetg.c
 putgetg.o: ./local_nc.h
 putgetg.o: ./netcdf.h
-rectest.o: rectest.c
-rectest.o: ./netcdf.h
-russ_bug.o: russ_bug.c
-russ_bug.o: ./netcdf.h
 sharray.o: sharray.c
 sharray.o: ./local_nc.h
 sharray.o: ./netcdf.h
 sharray.o: ./alloc.h
-stdio.o: stdio.c
 string.o: string.c
 string.o: ./local_nc.h
 string.o: ./netcdf.h
 string.o: ./alloc.h
-tbioread.o: tbioread.c
-tfread.o: tfread.c
-time-biowrite.o: time-biowrite.c
-time-fwrite.o: time-fwrite.c
-tposix.o: tposix.c
-tstdio.o: tstdio.c
-twrite.o: twrite.c
-ubioread.o: ubioread.c
-ubioread.o: ./timing.h
-ufread.o: ufread.c
-ufread.o: ./timing.h
-usgs.o: usgs.c
-usgs.o: ./netcdf.h
 var.o: var.c
 var.o: ./local_nc.h
 var.o: ./netcdf.h
 var.o: ./alloc.h
-version.o: version.c
-x.o: x.c
-x.o: ./local_nc.h
-x.o: ./netcdf.h
-x.o: ./alloc.h
 xdrposix.o: xdrposix.c
 xdrposix.o: ./netcdf.h
 xdrposix.o: ./local_nc.h
 xdrposix.o: ./netcdf.h
 xdrstdio.o: xdrstdio.c
-xdrstdio.o: ./netcdf.h
 xdrstdio.o: ./local_nc.h
 xdrstdio.o: ./netcdf.h
-xx.o: xx.c
-y.o: y.c
-y.o: ./netcdf.h
-zbioread.o: zbioread.c
-zbioread.o: ./timing.h
+xdrstdio.o: ./netcdf.h
+xdrstdio.o: ./local_nc.h
diff --git a/mfhdf/ncdump/Makefile b/mfhdf/ncdump/Makefile
--- a/mfhdf/ncdump/Makefile
+++ b/mfhdf/ncdump/Makefile
@@ -9,10 +9,11 @@ HDF_LIB         = /hdf/home/chouck/hdf/33/lib/libdf.a
 HDF_INC         = -I/hdf/home/chouck/hdf/33/include -DSUN
 CPP_NETCDF	= -I../libsrc -I../port $(HDF_INC)
 CPPFLAGS	= $(CPP_NETCDF) -DNDEBUG -DHDF -DNO_HAVE_PROTOTYPES -Dconst= -DNO_STDARG -DNO_STRERROR
-CFLAGS		= -O
-FFLAGS		= -O
+CFLAGS		= -g
+FFLAGS		= 
 MANIFEST	= Makefile.in ncdump.c ncdump.h  depend msoft.mk \
-		  test0.cdl vardata.c vardata.h dumplib.c dumplib.h ncdump.1
+		  test0.cdl vardata.c vardata.h dumplib.c dumplib.h ncdump.1 \
+                  make.com msofttab.c
 MANUALS		= ncdump.1
 LIBNAME		= netcdf
 LD_NETCDF	= -L../libsrc -l$(LIBNAME)
@@ -59,6 +60,7 @@ INSTALL		= /bin/install -c
 INSTALL_DATA	= $(INSTALL) -m 664
 INSTALL_PROGRAM	= $(INSTALL)
 FC		= f77
+MAKEINFO        = 
 NCDUMP		= @NCDUMP@
 NCGEN		= @NCGEN@
 NEQN		= neqn
@@ -390,6 +392,62 @@ dummy_mandir $(MANDIR):
 	mkdir -p $@
 	chmod u+rwx,g+rws,o=rx $@
 
+############################################################################
+# TeX-Info Pages:
+############################################################################
+INFODIR       = $(prefix)/info
+
+installed_infos:      FORCE
+	if [ -z "$(MAKEINFO)" ]; then \
+		echo 1>&2 "Can't install info(1) pages because no makeinfo(1)"; \
+	else \
+	  if [ -n "$(INFOS)" ]; then \
+	      infos="$(INFOS)"; \
+	      for info in $$infos; do \
+		$(MAKE) $(MFLAGS) INFODIR=$(INFODIR) INFO=$$info \
+		installed_info || exit 1; \
+	      done; \
+	   else \
+	      :; \
+	   fi; \
+	fi;
+# The following target decouples the previous targets from the actual rule;
+# thus, eliminating extraneous make(1) messages.
+#
+installed_info:       $(INFODIR)/$(INFO)
+
+$(INFODIR)/$(INFO):   $(INFODIR) $(INFO)
+	$(INSTALL_DATA) $(INFO) $@
+
+dummy_infodir $(INFODIR):
+	mkdir -p $@
+	chmod u+rwx,g+rws,o=rx $@
+
+# Rules for generating info pages:
+#
+.SUFFIXES:    .info .texi .texinfo .txn
+.texi.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.texinfo.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.txn.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+
+# Ensure that info page depends on canonical TeX-Info macros.
+#
+dummy_info $(INFO):   texinfo.tex
 
 ############################################################################
 # Cleanup:
@@ -514,6 +572,7 @@ MANIFEST.echo:	FORCE
 	    subdirs="$(SUBDIRS)"; \
 	    for subdir in $$subdirs; do \
 		(cd $$subdir && \
+                echo 1>&2 Creating $@ in `pwd` && \
 		$(MAKE) $(MFLAGS) MANIFEST.echo | \
 		    sed "s|^|$$subdir/|") || exit 1; \
 	    done; \
diff --git a/mfhdf/ncgen/Makefile.in b/mfhdf/ncgen/Makefile.in
--- a/mfhdf/ncgen/Makefile.in
+++ b/mfhdf/ncgen/Makefile.in
@@ -13,18 +13,19 @@ GARBAGE		= $(PROGRAM) \
 		  ncgenyy.c ncgentab.c ncgentab.h \
 		  test0.nc test1.nc test1.cdl test2.cdl test0.f ctest0 \
 		  ftest0 ftest0.nc ftest1.cdl test0.c ctest0.nc ctest1.cdl
+vms_stuff	= vmstab.c vmstab.h vms_yy.c
 MANIFEST	= Makefile.in depend README \
 		  close.c descrip.mms escapes.c generate.c generic.h \
 		  genlib.c genlib.h getfill.c init.c lexyacc.com load.c \
 		  main.c make.com msoft.mk msofttab.c msofttab.h \
 		  msoftyy.c ncgen.1 ncgen.h ncgen.l ncgen.opt ncgen.y \
-		  test.com test0.cdl
+		  test.com test0.cdl \
+                  $(vms_stuff)
 LIBNAME		= netcdf
 LD_NETCDF	= -L../libsrc -l$(LIBNAME)
 OBJS		= main.o generate.o load.o ncgentab.o escapes.o \
 		  getfill.o init.o close.o genlib.o
 LD_XDR		= @LD_XDR@
-LD_NETCDF	= -L../libsrc -lnetcdf
 LIBS		= $(LD_NETCDF) $(LD_XDR) @HDF_LIB@
 LEX		= @LEX@
 YACC		= @YACC@
@@ -32,13 +33,7 @@ prefix		= ../../..
 
 all::		$(PROGRAM)
 
-test:           $(PROGRAM) test0.cdl btest ctest FORCE
-	@if [ -n "$(FC)" ]; then \
-	    $(MAKE) $(MFLAGS) NCDUMP=$(NCDUMP) ftest; \
-	else \
-	    echo "\`ftest' not made because the make(1)-macro for" \
-		"the FORTRAN compiler (FC) is empty"; \
-	fi
+test:           $(PROGRAM) test0.cdl btest ctest ftest FORCE
 
 install::	installed_program installed_manuals
 
@@ -53,6 +48,13 @@ ncgentab.h:	ncgen.y ncgenyy.c ncgen.h
 ncgenyy.c:	ncgen.l
 	$(LEX) ncgen.l
 	mv lex.yy.c ncgenyy.c
+
+# The SunOS 4.1.3 yacc(1) doesn't generate correct code.
+#
+vms-stuff:    ncgentab.h ncgentab.c ncgenyy.c
+	cp ncgentab.h vmstab.h
+	cp ncgentab.c vmstab.c
+	cp ncgenyy.c vms_yy.c
 
 #
 # test "-b" option of ncgen
@@ -74,24 +76,34 @@ ctest:		test1.cdl ctest0
 
 ctest0:		ncgen test0.cdl
 	./$(PROGRAM) -c -o ctest0.nc test0.cdl > test0.c
-	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ test0.c $(LD_NETCDF) $(LIBS)
+	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ test0.c $(LIBS)
 
 #
 # test "-f" option of ncgen
 #
-ftest:		test1.cdl ftest0
-	./ftest0		# tests `-f' option, creates ftest0.nc
-	$(NCDUMP) -n test1 ftest0.nc > ftest1.cdl
-	@if diff test1.cdl ftest1.cdl; then \
-	    echo "*** ncgen -f test successful ***"; \
-	else \
-	    echo "*** ncgen -f test failed " \
-		"(but roundoff differences are OK) ***"; \
-	fi
+ftest:                test1.cdl
+        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
+            $(MAKE) $(MFLAGS) ftest0; \
+            ./ftest0            # tests `-f' option, creates ftest0.nc; \
+            $(NCDUMP) -n test1 ftest0.nc > ftest1.cdl; \
+            if diff test1.cdl ftest1.cdl; then \
+                echo "*** ncgen -f test successful ***"; \
+            else \
+                echo "*** ncgen -f test failed " \
+                    "(but roundoff differences are OK) ***"; \
+            fi; \
+        else \
+            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+        fi
 
-ftest0:		$(PROGRAM) test0.cdl netcdf.inc
-	./$(PROGRAM) -f -o ftest0.nc test0.cdl > test0.f
-	$(FC) $(FFLAGS) -o $@ test0.f $(LD_NETCDF) $(LIBS)
+ftest0:               $(PROGRAM) test0.cdl
+        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
+            $(MAKE) $(MFLAGS) netcdf.inc; \
+            ./$(PROGRAM) -f -o ftest0.nc test0.cdl > test0.f; \
+            $(FC) $(FFLAGS) -o $@ test0.f $(LIBS); \
+        else \
+            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+        fi
 
 test1.cdl:	test0.nc
 	$(NCDUMP) -n test1 test0.nc > $@
@@ -100,16 +112,11 @@ test0.nc:	$(PROGRAM) test0.cdl
 	./$(PROGRAM) -b -o test0.nc test0.cdl
 
 netcdf.inc:
-	ln -s ../fortran/$@ .
-
-msofttab.c : ncgentab.c
-	cp $? $@
-
-msofttab.h : ncgentab.h
-	cp $? $@
-
-msoftyy.c : ncgenyy.c
-	cp $? $@
+        @if [ `which "$(FC)" | wc -w` = 1 ]; then \
+            ln -s ../fortran/$@ .; \
+        else \
+            echo 1>&2 "\`$@' not made because no FORTRAN compiler"; \
+        fi
 
 include ../port/master.mk
 
diff --git a/mfhdf/port/Makefile b/mfhdf/port/Makefile
--- a/mfhdf/port/Makefile
+++ b/mfhdf/port/Makefile
@@ -8,15 +8,16 @@ LIBRARY		= udport
 MAJOR_NO	= 2
 MINOR_NO	= 
 
-CPPFLAGS	= -I. -DNDEBUG -DHDF -DNO_STRERROR
+CPPFLAGS	= -I. -DNDEBUG -DHDF -DNO_HAVE_PROTOTYPES -Dconst= -DNO_STDARG -DNO_STRERROR
 CFLAGS		= -g
 
 PORT_CFORTRAN	= @PORT_CFORTRAN@
 NEED_FORTC	= @NEED_FORTC@
 
 PORT_HEADERS	= 
-made_headers	= float.h limits.h signal.h stdarg.h stddef.h stdlib.h \
-		  string.h time.h
+config_headers	= signal.h stdarg.h stddef.h stdlib.h string.h time.h \
+		  udconfig.h udposix.h
+made_headers	= float.h limits.h
 LIBOBJS		= uddummy.o 
 
 prefix		= /hdf/home/chouck/hdf
@@ -24,8 +25,8 @@ prefix		= /hdf/home/chouck/hdf
 SUBDIRS		= 
 SUBDIR_TARGETS	= fortc/all fortc/install fortc/clean fortc/distclean
 MANIFEST        = COPYRIGHT CUSTOMIZE HISTORY Makefile.in VERSION aclocal.m4 \
-		  configure configure.in depend master.mk.in uddummy.c \
-		   udposix.h.in
+		   \
+		  configure configure.in depend master.mk.in uddummy.c
 
 # Note that the `all' target might not make `fortc/all'.  That will depend 
 # on whether or not that utility is required.
@@ -57,7 +58,7 @@ clean::		FORCE
 	else \
 	    :; \
 	fi
-	rm -f $(made_headers) $(PORT_HEADERS) config
+	rm -f $(made_headers) config
 
 distclean::
 	@if [ "$(NEED_FORTC)" = yes ]; then \
@@ -65,7 +66,7 @@ distclean::
 	else \
 	    :; \
 	fi
-	rm -f $(made_headers) $(PORT_HEADERS) config udposix.h master.mk
+	rm -f $(made_headers) $(config_headers) config master.mk
 
 Makefile:	Makefile.in master.mk.in
 
@@ -73,18 +74,6 @@ float.h:	config
 	./config -f > $@
 limits.h:	config
 	./config -l > $@
-signal.h:	signal.h.in
-	cp $? $@
-stdarg.h:	stdarg.h.in
-	cp $? $@
-stddef.h:	stddef.h.in
-	cp $? $@
-stdlib.h:	stdlib.h.in
-	cp $? $@
-string.h:	string.h.in
-	cp $? $@
-time.h:		time.h.in
-	cp $? $@
 cfortran.h:	cfortran_h
 	if test "$(PORT_CFORTRAN)" = stdc; then \
 	    sed 's/\/\*\*\//##/g' cfortran_h > $@; \
@@ -124,14 +113,15 @@ AR		= ar
 CC		= cc
 CPP		= cc -E
 INCDIR		= $(prefix)/include
-INSTALL		= cp
-INSTALL_DATA	= $(INSTALL)
+INSTALL		= /bin/install -c
+INSTALL_DATA	= $(INSTALL) -m 664
 INSTALL_PROGRAM	= $(INSTALL)
 FC		= f77
+MAKEINFO        = 
 NCDUMP		= @NCDUMP@
 NCGEN		= @NCGEN@
 NEQN		= neqn
-OS		= irix
+OS		= sunos
 SHELL		= /bin/sh
 TBL		= tbl
 
@@ -459,6 +449,62 @@ dummy_mandir $(MANDIR):
 	mkdir -p $@
 	chmod u+rwx,g+rws,o=rx $@
 
+############################################################################
+# TeX-Info Pages:
+############################################################################
+INFODIR       = $(prefix)/info
+
+installed_infos:      FORCE
+	if [ -z "$(MAKEINFO)" ]; then \
+		echo 1>&2 "Can't install info(1) pages because no makeinfo(1)"; \
+	else \
+	  if [ -n "$(INFOS)" ]; then \
+	      infos="$(INFOS)"; \
+	      for info in $$infos; do \
+		$(MAKE) $(MFLAGS) INFODIR=$(INFODIR) INFO=$$info \
+		installed_info || exit 1; \
+	      done; \
+	   else \
+	      :; \
+	   fi; \
+	fi;
+# The following target decouples the previous targets from the actual rule;
+# thus, eliminating extraneous make(1) messages.
+#
+installed_info:       $(INFODIR)/$(INFO)
+
+$(INFODIR)/$(INFO):   $(INFODIR) $(INFO)
+	$(INSTALL_DATA) $(INFO) $@
+
+dummy_infodir $(INFODIR):
+	mkdir -p $@
+	chmod u+rwx,g+rws,o=rx $@
+
+# Rules for generating info pages:
+#
+.SUFFIXES:    .info .texi .texinfo .txn
+.texi.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.texinfo.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+.txn.info:
+	@if [ -z "$(MAKEINFO)" ]; then \
+	  echo 1>&2 "Can't create $@ because no makeinfo(1)"; \
+	else \
+	  $(MAKEINFO) $< --no-split --output=$@; \
+	fi
+
+# Ensure that info page depends on canonical TeX-Info macros.
+#
+dummy_info $(INFO):   texinfo.tex
 
 ############################################################################
 # Cleanup:
@@ -583,6 +629,7 @@ MANIFEST.echo:	FORCE
 	    subdirs="$(SUBDIRS)"; \
 	    for subdir in $$subdirs; do \
 		(cd $$subdir && \
+                echo 1>&2 Creating $@ in `pwd` && \
 		$(MAKE) $(MFLAGS) MANIFEST.echo | \
 		    sed "s|^|$$subdir/|") || exit 1; \
 	    done; \
